# Generated by Django 5.0.6 on 2024-06-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAddedTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=255)),
                ('cars', models.CharField(max_length=255)),
                ('oxygen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(verbose_name='date paid')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.valueaddedtax')),
            ],
        ),
    ]
